// quotes.js
const myQuotes = [
  { text: "Sometimes your best investments are the ones you don't make.", author: "Donald Trump" },
  { text: "What separates the winners from the losers is how a person reacts to each new twist of fate.", author: "Donald Trump" },
  { text: "As long as you are going to be thinking anyway, think big.", author: "Donald Trump" },
  { text: "In the end, you're measured not by how much you undertake, but by what you finally accomplish.", author: "Donald Trump" },
  { text: "Money was never a big motivation for me, except as a way to keep score. The real excitement is playing the game.", author: "Donald Trump" },
  { text: "Sometimes by losing a battle you find a new way to win the war.", author: "Donald Trump" },
  { text: "Nothing great in the world has been accomplished without passion.", author: "Donald Trump" },
  { text: "My whole life is about winning. I don't lose often. I almost never lose.", author: "Donald Trump" },
  { text: "No dream is too big. No challenge is too great. Nothing we want for our future is beyond our reach.", author: "Donald Trump" },
  { text: "Success comes from failure, not from memorizing the right answers.", author: "Donald Trump" },
  { text: "Leaders, true leaders, take responsibility for the success of the team, and understand that they must also take responsibility for the failure.", author: "Donald Trump" },
  { text: "I don't hire a lot of number-crunchers, and I don't trust fancy marketing surveys. I do my own surveys and draw my own conclusions.", author: "Donald Trump" },
  { text: "Your business, and your brand, must first let people know what you care about, and that you care about them.", author: "Donald Trump" },
  { text: "I will build a great, great wall on our southern border, and I will make Mexico pay for that wall. Mark my words.", author: "Donald Trump" },
  { text: "I beat China all the time. All the time.", author: "Donald Trump" },
  { text: "If you are a little different, or a little outrageous, or if you do things that are bold or controversial, the press is going to write about you.", author: "Donald Trump" },
  { text: "Criticism is easier to take when you realize that the only people who aren't criticized are those who don't take risks.", author: "Donald Trump" },
  { text: "You know, it doesn't really matter what they write as long as you've got a young and beautiful piece of ass.", author: "Donald Trump" },
  { text: "I'm the Ernest Hemingway of 140 characters.", author: "Donald Trump" },
  { text: "Our country is in serious trouble. We don't have victories anymore.", author: "Donald Trump" },
  { text: "When Mexico sends its people, they're not sending their best... They're sending people that have lots of problems, and they're bringing those problems with us. They're bringing drugs. They're bringing crime. They're rapists. And some, I assume, are good people.", author: "Donald Trump" },
  { text: "We will make America strong again. We will make America proud again. We will make America safe again. And we will make America great again.", author: "Donald Trump" },
  { text: "The most basic duty of government is to defend the lives of its own citizens. Any government that fails to do so is a government unworthy to lead.", author: "Donald Trump" },
  { text: "I have no patience for injustice, no tolerance for government incompetence, no sympathy for leaders who fail their citizens.", author: "Donald Trump" },
  { text: "I think apologizing's a great thing, but you have to be wrong. I will absolutely apologize, sometime in the hopefully distant future, if I'm ever wrong.", author: "Donald Trump" },
  { text: "Sorry losers and haters, but my I.Q. is one of the highest – and you all know it! Please don't feel so stupid or insecure, it's not your fault.", author: "Donald Trump" },
  { text: "The beauty of me is that I'm very rich.", author: "Donald Trump" },
  { text: "Anyone who thinks my story is anywhere near over is sadly mistaken.", author: "Donald Trump" },
  { text: "He's not a war hero. He was a war hero because he was captured. I like people who weren't captured.", author: "Donald Trump" },
  { text: "We are up BIG, but they are trying to STEAL the Election. We will never let them do it. Votes cannot be cast after the Polls are closed!", author: "Donald Trump" }
];